<a href="https://colab.research.google.com/github/huihuiwuwu/Github-Colab/blob/main/%EC%A0%81%EC%86%8C_%EA%B2%BD%EC%9F%81%EC%9A%B0%EC%9C%84_%EA%B3%84%EC%82%B0%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import re
from tqdm import tqdm
import pandas as pd
import os

In [ ]:
facebook=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/facebook.xlsx")
ins=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/ins.xlsx")
meta=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/meta_수정.xlsx")
youtube=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/youtube.xlsx")

In [ ]:
print(facebook.head(),
ins.head(),
youtube.head(),
meta.head()
)

   정보1  정보2  정보3  정보4  정보5  오락1  오락2  오락3  오락4  개인화2  개인화3  개인화4  상호작용2  \
0    5    5    6    6    5    5    5    5    5     5     5     4      3
1    4    5    5    5    5    4    5    3    2     3     3     3      2
2    5    6    6    6    6    2    4    3    3     2     2     3      3
3    4    5    7    7    7    4    7    7    7     4     4     6      7
4    6    6    6    6    6    4    5    6    6     6     5     5      4

   상호작용3  상호작용4  상호작용5  만족1  만족2  만족3  만족4
0      3      3      3    5    6    7    7
1      4      3      3    4    5    4    4
2      3      2      3    6    5    5    4
3      7      7      7    7    7    6    6
4      5      5      5    4    4    4    5      정보1  정보2  정보3  정보4  정보5  오락1  오락2  오락3  오락4  개인화2  개인화3  개인화4  상호작용2  \
0    4    5    5    6    5    5    5    5    6     5     4     5      5
1    1    1    4    4    1    4    7    7    7     7     4     4      7
2    1    7    7    7    3    4    4    3    4     3     5     2      5
3    7    4    5    5    4    4    4    2    2     2     4     2      2
4    5    3    5    5    6    3    3    3    3     3     3     4      3

   상호작용3  상호작용4  상호작용5  만족1  만족2  만족3  만족4
0      5      5      5    4    4    5    5
1      7      7      7    4    4    4    4
2      5      5      6    6    6    6    7
3      2      2      2    5    5    5    5
4      4      3      1    3    3    3    3      정보1  정보2  정보3  정보4  정보5  오락1  오락2  오락3  오락4  개인화2  개인화3  개인화4  상호작용2  \
0    4    5    7    7    7    6    4    4    5     4     5     4      5
1    7    7    7    7    7    6    3    7    4     6     6     6      3
2    7    7    7    7    7    6    6    6    6     5     5     4      5
3    5    5    4    4    2    3    4    2    2     3     3     2      3
4    3    3    5    4    3    5    3    3    3     3     3     2      3

   상호작용3  상호작용4  상호작용5  만족1  만족2  만족3  만족4
0      2      2      2    6    3    4    6
1      3      2      3    6    6    6    6
2      7      7      6    4    5    5    4
3      4      5      6    3    4    5    6
4      3      3      3    4    3    3    3      정보1  정보2  정보3  정보4  정보5  오락1  오락2  오락3  오락4  상호작용1  상호작용2  상호작용3  상호작용4  \
0    5    5    6    4    4    6    7    7    7      7      3      4      5
1    5    5    6    5    6    3    1    5    5      3      2      5      3
2    3    4    5    2    4    5    5    4    5      5      6      6      6
3    5    5    4    4    3    5    5    5    5      6      5      5      4
4    5    6    6    6    6    6    6    6    6      3      5      2      4

   개인화1  개인화2  개인화3  만족1  만족2  만족3  만족4
0     6     5     6    4    3    5    6
1     6     4     4    5    3    2    4
2     4     3     4    4    5    4    5
3     5     4     4    5    4    5    5
4     2     3     3    2    1    1    1

In [ ]:
def rename_columns(df):
    rename_dict = {
        '개인화2': '개인화1',
        '개인화3': '개인화2',
        '개인화4': '개인화3',
        '상호작용2': '상호작용1',
        '상호작용3': '상호작용2',
        '상호작용4': '상호작용3',
        '상호작용5': '상호작용4'
    }
    return df.rename(columns=rename_dict)


facebook_df = rename_columns(facebook)
ins_df = rename_columns(ins)
youtube_df = rename_columns(youtube)
meta_df=rename_columns(meta)

In [ ]:
youtube_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,개인화1,개인화2,개인화3,상호작용1,상호작용2,상호작용3,상호작용4,만족1,만족2,만족3,만족4
0,4,5,7,7,7,6,4,4,5,4,5,4,5,2,2,2,6,3,4,6
1,7,7,7,7,7,6,3,7,4,6,6,6,3,3,2,3,6,6,6,6
2,7,7,7,7,7,6,6,6,6,5,5,4,5,7,7,6,4,5,5,4
3,5,5,4,4,2,3,4,2,2,3,3,2,3,4,5,6,3,4,5,6
4,3,3,5,4,3,5,3,3,3,3,3,2,3,3,3,3,4,3,3,3

In [ ]:

def calculate_competitive_advantage(facebook_df, ins_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = facebook_df.iloc[:, start_index:start_index + measurements].gt(
                            ins_df.iloc[:, start_index:start_index + measurements]).multiply(
                            facebook_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = ins_df.iloc[:, start_index:start_index + measurements].gt(
                            facebook_df.iloc[:, start_index:start_index + measurements]).multiply(
                            ins_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(facebook_df),
            'S_j_greater_i': M_j_greater_i / len(ins_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage

# Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
num_variables = [5, 4, 3, 4, 4]

# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(facebook_df, ins_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 1989,
  'M_j_greater_i': 2124,
  'S_i_greater_j': 11.431034482758621,
  'S_j_greater_i': 12.206896551724139},
 '오락': {'M_i_greater_j': 1447,
  'M_j_greater_i': 1732,
  'S_i_greater_j': 8.316091954022989,
  'S_j_greater_i': 9.954022988505747},
 '개인화': {'M_i_greater_j': 1099,
  'M_j_greater_i': 1236,
  'S_i_greater_j': 6.316091954022989,
  'S_j_greater_i': 7.103448275862069},
 '상호작용': {'M_i_greater_j': 1265,
  'M_j_greater_i': 2016,
  'S_i_greater_j': 7.2701149425287355,
  'S_j_greater_i': 11.586206896551724},
 '만족': {'M_i_greater_j': 1725,
  'M_j_greater_i': 1698,
  'S_i_greater_j': 9.913793103448276,
  'S_j_greater_i': 9.758620689655173}}

In [ ]:

def calculate_competitive_advantage(facebook_df, youtube_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = facebook_df.iloc[:, start_index:start_index + measurements].gt(
                            youtube_df.iloc[:, start_index:start_index + measurements]).multiply(
                            facebook_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = youtube_df.iloc[:, start_index:start_index + measurements].gt(
                            facebook_df.iloc[:, start_index:start_index + measurements]).multiply(
                            youtube_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(facebook_df),
            'S_j_greater_i': M_j_greater_i / len(youtube_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage

# Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
num_variables = [5, 4, 3, 4, 4]

# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(facebook_df, youtube_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2092,
  'M_j_greater_i': 2077,
  'S_i_greater_j': 12.022988505747126,
  'S_j_greater_i': 11.936781609195402},
 '오락': {'M_i_greater_j': 1474,
  'M_j_greater_i': 1681,
  'S_i_greater_j': 8.471264367816092,
  'S_j_greater_i': 9.660919540229886},
 '개인화': {'M_i_greater_j': 989,
  'M_j_greater_i': 1352,
  'S_i_greater_j': 5.683908045977011,
  'S_j_greater_i': 7.7701149425287355},
 '상호작용': {'M_i_greater_j': 1380,
  'M_j_greater_i': 1714,
  'S_i_greater_j': 7.931034482758621,
  'S_j_greater_i': 9.850574712643677},
 '만족': {'M_i_greater_j': 1612,
  'M_j_greater_i': 1735,
  'S_i_greater_j': 9.264367816091953,
  'S_j_greater_i': 9.971264367816092}}

In [ ]:

def calculate_competitive_advantage(ins_df, youtube_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = ins_df.iloc[:, start_index:start_index + measurements].gt(
                            youtube_df.iloc[:, start_index:start_index + measurements]).multiply(
                            ins_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = youtube_df.iloc[:, start_index:start_index + measurements].gt(
                            ins_df.iloc[:, start_index:start_index + measurements]).multiply(
                            youtube_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(ins_df),
            'S_j_greater_i': M_j_greater_i / len(youtube_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage

# Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
num_variables = [5, 4, 3, 4, 4]

# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(ins_df, youtube_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2313,
  'M_j_greater_i': 1793,
  'S_i_greater_j': 13.293103448275861,
  'S_j_greater_i': 10.304597701149426},
 '오락': {'M_i_greater_j': 1565,
  'M_j_greater_i': 1600,
  'S_i_greater_j': 8.994252873563218,
  'S_j_greater_i': 9.195402298850574},
 '개인화': {'M_i_greater_j': 1012,
  'M_j_greater_i': 1235,
  'S_i_greater_j': 5.816091954022989,
  'S_j_greater_i': 7.097701149425287},
 '상호작용': {'M_i_greater_j': 1923,
  'M_j_greater_i': 1432,
  'S_i_greater_j': 11.051724137931034,
  'S_j_greater_i': 8.229885057471265},
 '만족': {'M_i_greater_j': 1646,
  'M_j_greater_i': 1639,
  'S_i_greater_j': 9.459770114942529,
  'S_j_greater_i': 9.419540229885058}}

In [ ]:

def calculate_variable_averages(df, num_measurements):
    averages = {}
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']
    start_index = 0

    # calculate the average
    for i, (variable, num) in enumerate(zip(variable_names, num_measurements)):

        columns = df.iloc[:, start_index:start_index + num]

        averages[variable] = columns.mean().mean()

        start_index += num

    return averages

In [ ]:
# calculate the average value of Facebook, INS, YouTube
averages_facebook = calculate_variable_averages(facebook, num_variables)
averages_ins = calculate_variable_averages(ins, num_variables)
averages_youtube = calculate_variable_averages(youtube, num_variables)

averages_facebook, averages_ins, averages_youtube

({'정보': 5.231034482758621,
  '오락': 4.294540229885057,
  '상호작용': 4.169540229885057,
  '개인화': 4.160919540229885,
  '만족': 5.09051724137931},
 {'정보': 5.325287356321839,
  '오락': 4.425287356321839,
  '상호작용': 4.380747126436781,
  '개인화': 4.74904214559387,
  '만족': 5.1048850574712645},
 {'정보': 5.113793103448275,
  '오락': 4.445402298850574,
  '상호작용': 4.511494252873563,
  '개인화': 4.563218390804598,
  '만족': 5.096264367816092})

In [ ]:

num_variables = [5, 4, 4, 3, 4]
variable_names = ['정보', '오락', '상호작용', '개인화', '만족']

# calculate the average value
def calculate_averages_per_variable(df, num_variables):
    start_col = 0
    averages = {}
    for num_measure, var_name in zip(num_variables, variable_names):
        # Select the columns for each variable and calculate the mean
        var_columns = df.iloc[:, start_col:start_col + num_measure]
        var_mean = var_columns.mean(axis=1)  # Calculate the mean across the columns (axis=1)
        averages[var_name] = var_mean.mean()  # Calculate the mean across all respondents
        start_col += num_measure  # Move to the next set of columns for the next variable
    return averages

# Facebook
facebook_averages = calculate_averages_per_variable(facebook_df, num_variables)

# INS
ins_averages = calculate_averages_per_variable(ins_df, num_variables)

# YouTube
youtube_averages = calculate_averages_per_variable(youtube_df, num_variables)

facebook_averages, ins_averages, youtube_averages

In [ ]:
len(combined_mean)

20

In [ ]:
# calculate the competitive value
def calculate_competitive_advantage(ins, youtube, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '상호작용', '개인화', '만족']

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = ins.iloc[:, start_index:start_index + measurements].gt(
                            youtube.iloc[:, start_index:start_index + measurements]).multiply(
                            ins.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = youtube.iloc[:, start_index:start_index + measurements].gt(
                            ins.iloc[:, start_index:start_index + measurements]).multiply(
                            youtube.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(ins),
            'S_j_greater_i': M_j_greater_i / len(youtube)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage

# Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
num_variables = [5, 4, 4, 3, 4]

# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(ins, youtube, num_variables)

comp_adv_fb_ins

In [ ]:
import numpy as np
# Assuming facebook_df, ins_df, and youtube_df are your dataframes for each platform
# First, define the indices for the start of each variable based on the number of measurements
variable_indices = np.cumsum([0] + num_variables)[:-1]

# Then, for each dataframe, calculate the mean for each variable for each respondent
def calculate_variable_means(df, variable_indices, num_variables):
    variable_means = pd.DataFrame()
    for start, num in zip(variable_indices, num_variables):
        # Calculate the mean for each variable across its measurements
        variable_means = pd.concat([variable_means, df.iloc[:, start:start+num].mean(axis=1)], axis=1)
    return variable_means

In [ ]:
variable_names = ['정보', '오락', '상호작용', '개인화', '만족']
num_varibales = [5, 4, 4, 3, 4]  # Number of measurements for each variable

# Calculate the means for each platform
facebook_variable_means = calculate_variable_means(facebook, variable_indices, num_variables)
ins_variable_means = calculate_variable_means(ins, variable_indices, num_variables)
youtube_variable_means = calculate_variable_means(youtube, variable_indices, num_variables)

# Combine the means into a single DataFrame for comparison
combined_means = pd.concat([facebook_variable_means, ins_variable_means, youtube_variable_means], axis=1)
combined_means.columns = ['Facebook_' + var for var in variable_names] + \
                         ['INS_' + var for var in variable_names] + \
                         ['YouTube_' + var for var in variable_names]

combined_means.head()

,Facebook_정보,Facebook_오락,Facebook_상호작용,Facebook_개인화,Facebook_만족,INS_정보,INS_오락,INS_상호작용,INS_개인화,INS_만족,YouTube_정보,YouTube_오락,YouTube_상호작용,YouTube_개인화,YouTube_만족
0,5.4,5.00,4.25,3.000000,6.25,5.0,5.25,4.75,5.000000,4.50,6.0,4.75,4.50,2.000000,4.75
1,4.8,3.50,2.75,3.333333,4.25,2.2,6.25,5.50,7.000000,4.00,7.0,5.00,5.25,2.666667,6.00
2,5.8,3.00,2.50,2.666667,5.00,5.0,3.75,3.75,5.333333,6.25,7.0,6.00,4.75,6.666667,4.50
3,6.0,6.25,5.25,7.000000,6.50,5.0,3.00,2.50,2.000000,5.00,4.0,2.75,2.75,5.000000,4.50
4,6.0,5.25,5.00,5.000000,4.25,4.8,3.00,3.25,2.666667,3.00,3.6,3.50,2.75,3.000000,3.25

In [ ]:
variable_names = ['정보', '오락', '개인화', '상호작용', '만족']
num_varibales = [5, 4, 3, 4, 4]  # Number of measurements for each variable

# Calculate the means for each platform
facebook_variable_means = calculate_variable_means(facebook_df, variable_indices, num_variables)
ins_variable_means = calculate_variable_means(ins_df, variable_indices, num_variables)
youtube_variable_means = calculate_variable_means(youtube_df, variable_indices, num_variables)

# Combine the means into a single DataFrame for comparison
combined_means = pd.concat([facebook_variable_means, ins_variable_means, youtube_variable_means], axis=1)
combined_means.columns = ['Facebook_' + var for var in variable_names] + \
                         ['INS_' + var for var in variable_names] + \
                         ['YouTube_' + var for var in variable_names]

combined_means.head()

,Facebook_정보,Facebook_오락,Facebook_개인화,Facebook_상호작용,Facebook_만족,INS_정보,INS_오락,INS_개인화,INS_상호작용,INS_만족,YouTube_정보,YouTube_오락,YouTube_개인화,YouTube_상호작용,YouTube_만족
0,5.4,5.00,4.666667,3.00,6.25,5.0,5.25,4.666667,5.00,4.50,6.0,4.75,4.333333,2.75,4.75
1,4.8,3.50,3.000000,3.00,4.25,2.2,6.25,5.000000,7.00,4.00,7.0,5.00,6.000000,2.75,6.00
2,5.8,3.00,2.333333,2.75,5.00,5.0,3.75,3.333333,5.25,6.25,7.0,6.00,4.666667,6.25,4.50
3,6.0,6.25,4.666667,7.00,6.50,5.0,3.00,2.666667,2.00,5.00,4.0,2.75,2.666667,4.50,4.50
4,6.0,5.25,5.333333,4.75,4.25,4.8,3.00,3.333333,2.75,3.00,3.6,3.50,2.666667,3.00,3.25

In [ ]:
combined_means.to_csv("/content/drive/MyDrive/최근/적소이론/20231120/combibed_means(수정).csv",index=False)

In [ ]:

def calculate_row_variable_means(df):

    row_variable_means = pd.DataFrame()

    for variable in ['정보', '오락', '개인화', '상호작용', '만족']:
        variable_columns = [col for col in df.columns if variable in col]
        row_variable_means[variable] = df[variable_columns].mean(axis=1)

        row_variable_means = row_variable_means.astype(int)

    return row_variable_means

In [ ]:


row_variable_means = calculate_row_variable_means(combined_means)

print(row_variable_means.head())

   정보  오락  상호작용  개인화  만족
0   5   5     4    3   5
1   4   4     4    4   4
2   5   4     3    4   5
3   5   4     3    4   5
4   4   3     3    3   3

In [ ]:
row_variable_means.to_csv("/content/drive/MyDrive/최근/적소이론/20231120/row_variable_means.csv",index=False)

In [ ]:
SNS=pd.read_csv("/content/drive/MyDrive/최근/적소이론/20231120/row_variable_means.csv")

In [ ]:
SNS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   정보      174 non-null    int64
 1   오락      174 non-null    int64
 2   상호작용    174 non-null    int64
 3   개인화     174 non-null    int64
 4   만족      174 non-null    int64
dtypes: int64(5)
memory usage: 6.9 KB

In [ ]:
SNS.head()

   정보  오락  상호작용  개인화  만족
0   5   5     4    3   5
1   4   4     4    4   4
2   5   4     3    4   5
3   5   4     3    4   5
4   4   3     3    3   3

In [ ]:

variable_indices = np.cumsum([0] + num_varibales)[:-1]

def calculate_means_for_variables(df, variable_names, num_varibales):
    combined_variable_means = pd.DataFrame()
    for var_name, num_measure in zip(variable_names, num_varibales):
        variable_columns = [f'{var_name}{i+1}' for i in range(num_measure)]
        combined_variable_means[var_name] = df[variable_columns].mean(axis=1)
    return combined_variable_means

In [ ]:

facebook_means = calculate_means_for_variables(facebook_df, variable_names, num_varibales)
ins_means = calculate_means_for_variables(ins_df, variable_names, num_varibales)
youtube_means = calculate_means_for_variables(youtube_df, variable_names, num_varibales)

combined_means = pd.concat([facebook_means, ins_means, youtube_means], axis=1)

combined_means.columns = [f'Facebook_{var}' for var in variable_names] + \
                         [f'INS_{var}' for var in variable_names] + \
                         [f'YouTube_{var}' for var in variable_names]

# 查看组合后的平均值 DataFrame 的前几行
combined_means.head()

,Facebook_정보,Facebook_오락,Facebook_상호작용,Facebook_개인화,Facebook_만족,INS_정보,INS_오락,INS_상호작용,INS_개인화,INS_만족,YouTube_정보,YouTube_오락,YouTube_상호작용,YouTube_개인화,YouTube_만족
0,5.4,5.00,3.00,4.666667,6.25,5.0,5.25,5.00,4.666667,4.50,6.0,4.75,2.75,4.333333,4.75
1,4.8,3.50,3.00,3.000000,4.25,2.2,6.25,7.00,5.000000,4.00,7.0,5.00,2.75,6.000000,6.00
2,5.8,3.00,2.75,2.333333,5.00,5.0,3.75,5.25,3.333333,6.25,7.0,6.00,6.25,4.666667,4.50
3,6.0,6.25,7.00,4.666667,6.50,5.0,3.00,2.00,2.666667,5.00,4.0,2.75,4.50,2.666667,4.50
4,6.0,5.25,4.75,5.333333,4.25,4.8,3.00,2.75,3.333333,3.00,3.6,3.50,3.00,2.666667,3.25

In [ ]:
combined_means

,Facebook_정보,Facebook_오락,Facebook_상호작용,Facebook_개인화,Facebook_만족,INS_정보,INS_오락,INS_상호작용,INS_개인화,INS_만족,YouTube_정보,YouTube_오락,YouTube_상호작용,YouTube_개인화,YouTube_만족
0,5.4,5.00,3.00,4.666667,6.25,5.0,5.25,5.00,4.666667,4.50,6.0,4.75,2.75,4.333333,4.75
1,4.8,3.50,3.00,3.000000,4.25,2.2,6.25,7.00,5.000000,4.00,7.0,5.00,2.75,6.000000,6.00
2,5.8,3.00,2.75,2.333333,5.00,5.0,3.75,5.25,3.333333,6.25,7.0,6.00,6.25,4.666667,4.50
3,6.0,6.25,7.00,4.666667,6.50,5.0,3.00,2.00,2.666667,5.00,4.0,2.75,4.50,2.666667,4.50
4,6.0,5.25,4.75,5.333333,4.25,4.8,3.00,2.75,3.333333,3.00,3.6,3.50,3.00,2.666667,3.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,2.2,2.50,2.25,1.333333,1.00,5.6,4.75,4.00,5.333333,3.50,5.0,2.00,6.00,5.000000,4.50
170,3.8,3.50,5.50,2.000000,4.75,5.0,2.00,5.50,2.666667,4.50,4.8,4.00,4.00,4.666667,3.50
171,5.8,4.25,5.00,5.000000,5.25,5.8,5.25,3.00,6.333333,6.75,4.0,6.50,5.25,3.666667,5.00
172,4.4,4.25,5.00,5.333333,3.50,5.2,4.50,4.25,5.000000,6.00,4.6,5.25,4.75,4.666667,4.25
173,6.0,4.25,3.50,3.333333,3.25,4.8,5.50,4.50,5.333333,5.50,5.6,2.75,4.50,5.000000,4.75

In [ ]:
variable_names = ['정보', '오락', '상호작용', '개인화', '만족']
num_measurements = [5, 4, 4, 3, 4]  # Number of measurements for each variable

measurement_columns = []
for name, count in zip(variable_names, num_measurements):
    measurement_columns.extend([f'{name}{i}' for i in range(1, count+1)])


# Initialize a dictionary to hold the averages for each measurement
averages = {}

# Now calculate the averages across the three platforms for each measurement
for column in measurement_columns:
    # Use the .filter() method to select columns for the current measurement
    facebook_info_cols = facebook_df.filter(like=column)
    ins_info_cols = ins_df.filter(like=column)
    youtube_info_cols = youtube_df.filter(like=column)

    # Ensure we have only one column from each DataFrame, then calculate the mean
    if len(facebook_info_cols.columns) == len(ins_info_cols.columns) == len(youtube_info_cols.columns) == 1:
        averages[column] = (facebook_info_cols.iloc[:, 0] + ins_info_cols.iloc[:, 0] + youtube_info_cols.iloc[:, 0]) / 3

# Convert the averages dictionary to a DataFrame
averages_df = pd.DataFrame(averages)

# Display the DataFrame to verify the results
averages_df

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,상호작용1,상호작용2,상호작용3,상호작용4,개인화1,개인화2,개인화3,만족1,만족2,만족3,만족4
0,4.333333,5.000000,6.000000,6.333333,5.666667,5.333333,4.666667,4.666667,5.333333,4.333333,3.333333,3.333333,3.333333,4.666667,4.666667,4.333333,5.000000,4.333333,5.333333,6.000000
1,4.000000,4.333333,5.333333,5.333333,4.333333,4.666667,5.000000,5.666667,4.333333,4.000000,4.666667,4.000000,4.333333,5.333333,4.333333,4.333333,4.666667,5.000000,4.666667,4.666667
2,4.333333,6.666667,6.666667,6.666667,5.333333,4.000000,4.666667,4.000000,4.333333,4.333333,5.000000,4.666667,5.000000,3.333333,4.000000,3.000000,5.333333,5.333333,5.333333,5.000000
3,5.333333,4.666667,5.333333,5.333333,4.333333,3.666667,5.000000,3.666667,3.666667,4.000000,4.333333,4.666667,5.000000,3.000000,3.666667,3.333333,5.000000,5.333333,5.333333,5.666667
4,4.666667,4.000000,5.333333,5.000000,5.000000,4.000000,3.666667,4.000000,4.000000,3.333333,4.000000,3.666667,3.000000,4.000000,3.666667,3.666667,3.666667,3.333333,3.333333,3.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,3.333333,4.666667,5.666667,3.666667,4.000000,4.000000,3.666667,2.666667,2.000000,4.000000,4.000000,4.333333,4.000000,4.000000,4.000000,3.666667,2.666667,3.666667,2.666667,3.000000
170,3.333333,4.333333,5.333333,5.000000,4.666667,3.000000,3.666667,3.000000,3.000000,4.333333,5.000000,5.333333,5.333333,3.000000,3.666667,2.666667,4.333333,4.333333,4.333333,4.000000
171,5.333333,5.333333,5.000000,5.333333,5.000000,5.666667,5.000000,5.333333,5.333333,4.333333,5.333333,4.000000,4.000000,5.000000,5.000000,5.000000,5.333333,5.666667,5.666667,6.000000
172,5.000000,4.666667,3.666667,5.000000,5.333333,4.666667,5.333333,3.333333,5.333333,5.000000,5.000000,4.000000,4.666667,4.666667,6.000000,4.333333,5.000000,4.000000,5.000000,4.333333
173,5.666667,5.666667,5.666667,5.666667,4.666667,4.333333,3.333333,4.666667,4.333333,5.000000,3.000000,4.000000,4.666667,4.666667,4.333333,4.666667,4.333333,4.333333,4.666667,4.666667

In [ ]:
rounded_df = averages_df.round().astype(int)

In [ ]:
rounded_df

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,상호작용1,상호작용2,상호작용3,상호작용4,개인화1,개인화2,개인화3,만족1,만족2,만족3,만족4
0,4,5,6,6,6,5,5,5,5,4,3,3,3,5,5,4,5,4,5,6
1,4,4,5,5,4,5,5,6,4,4,5,4,4,5,4,4,5,5,5,5
2,4,7,7,7,5,4,5,4,4,4,5,5,5,3,4,3,5,5,5,5
3,5,5,5,5,4,4,5,4,4,4,4,5,5,3,4,3,5,5,5,6
4,5,4,5,5,5,4,4,4,4,3,4,4,3,4,4,4,4,3,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,3,5,6,4,4,4,4,3,2,4,4,4,4,4,4,4,3,4,3,3
170,3,4,5,5,5,3,4,3,3,4,5,5,5,3,4,3,4,4,4,4
171,5,5,5,5,5,6,5,5,5,4,5,4,4,5,5,5,5,6,6,6
172,5,5,4,5,5,5,5,3,5,5,5,4,5,5,6,4,5,4,5,4
173,6,6,6,6,5,4,3,5,4,5,3,4,5,5,4,5,4,4,5,5

In [ ]:
meta_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,상호작용1,상호작용1,상호작용2,상호작용3,개인화1,개인화1,개인화2,만족1,만족2,만족3,만족4
0,5,5,6,4,4,6,7,7,7,7,3,4,5,6,5,6,4,3,5,6
1,5,5,6,5,6,3,1,5,5,3,2,5,3,6,4,4,5,3,2,4
2,3,4,5,2,4,5,5,4,5,5,6,6,6,4,3,4,4,5,4,5
3,5,5,4,4,3,5,5,5,5,6,5,5,4,5,4,4,5,4,5,5
4,5,6,6,6,6,6,6,6,6,3,5,2,4,2,3,3,2,1,1,1

In [ ]:
rounded_df.to_csv("/content/drive/MyDrive/최근/적소이론/20231120/평균SNS.csv",index=False)

In [ ]:
SNS_df=pd.read_csv("/content/drive/MyDrive/최근/적소이론/20231120/평균SNS.csv")

In [ ]:
SNS_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,상호작용1,상호작용2,상호작용3,상호작용4,개인화1,개인화2,개인화3,만족1,만족2,만족3,만족4
0,4,5,6,6,6,5,5,5,5,4,3,3,3,5,5,4,5,4,5,6
1,4,4,5,5,4,5,5,6,4,4,5,4,4,5,4,4,5,5,5,5
2,4,7,7,7,5,4,5,4,4,4,5,5,5,3,4,3,5,5,5,5
3,5,5,5,5,4,4,5,4,4,4,4,5,5,3,4,3,5,5,5,6
4,5,4,5,5,5,4,4,4,4,3,4,4,3,4,4,4,4,3,3,4

In [ ]:
meta=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/meta_수정.xlsx")

In [ ]:
meta.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,상호작용1,상호작용2,상호작용3,상호작용4,개인화1,개인화2,개인화3,만족1,만족2,만족3,만족4
0,5,5,6,4,4,6,7,7,7,7,3,4,5,6,5,6,4,3,5,6
1,5,5,6,5,6,3,1,5,5,3,2,5,3,6,4,4,5,3,2,4
2,3,4,5,2,4,5,5,4,5,5,6,6,6,4,3,4,4,5,4,5
3,5,5,4,4,3,5,5,5,5,6,5,5,4,5,4,4,5,4,5,5
4,5,6,6,6,6,6,6,6,6,3,5,2,4,2,3,3,2,1,1,1

In [ ]:
# SNS VS meta

def calculate_competitive_advantage(SNS_df, meta, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '상호작용', '개인화', '만족']

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = SNS_df.iloc[:, start_index:start_index + measurements].gt(
                            meta.iloc[:, start_index:start_index + measurements]).multiply(
                            SNS_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = meta.iloc[:, start_index:start_index + measurements].gt(
                            SNS_df.iloc[:, start_index:start_index + measurements]).multiply(
                            meta.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(SNS_df),
            'S_j_greater_i': M_j_greater_i / len(meta)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage

# Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
num_variables = [5, 4, 4, 3, 4]

# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(SNS_df, meta, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2547,
  'M_j_greater_i': 1277,
  'S_i_greater_j': 14.637931034482758,
  'S_j_greater_i': 7.339080459770115},
 '오락': {'M_i_greater_j': 1108,
  'M_j_greater_i': 1873,
  'S_i_greater_j': 6.367816091954023,
  'S_j_greater_i': 10.764367816091953},
 '상호작용': {'M_i_greater_j': 774,
  'M_j_greater_i': 2484,
  'S_i_greater_j': 4.448275862068965,
  'S_j_greater_i': 14.275862068965518},
 '개인화': {'M_i_greater_j': 1072,
  'M_j_greater_i': 806,
  'S_i_greater_j': 6.160919540229885,
  'S_j_greater_i': 4.632183908045977},
 '만족': {'M_i_greater_j': 1340,
  'M_j_greater_i': 1650,
  'S_i_greater_j': 7.7011494252873565,
  'S_j_greater_i': 9.482758620689655}}

In [ ]:
facebook_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,개인화1,개인화2,개인화3,상호작용1,상호작용2,상호작용3,상호작용4,만족1,만족2,만족3,만족4
0,5,5,6,6,5,5,5,5,5,5,5,4,3,3,3,3,5,6,7,7
1,4,5,5,5,5,4,5,3,2,3,3,3,2,4,3,3,4,5,4,4
2,5,6,6,6,6,2,4,3,3,2,2,3,3,3,2,3,6,5,5,4
3,4,5,7,7,7,4,7,7,7,4,4,6,7,7,7,7,7,7,6,6
4,6,6,6,6,6,4,5,6,6,6,5,5,4,5,5,5,4,4,4,5

In [ ]:
meta1=pd.read_excel("/content/drive/MyDrive/최근/적소이론/20231120/meta.xlsx")
meta1_df=rename_columns(meta1)

In [ ]:
meta1_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,개인화1,개인화2,개인화3,상호작용1,상호작용2,상호작용3,상호작용4,만족1,만족2,만족3,만족4
0,5,5,6,4,4,6,7,7,7,6,5,6,7,3,4,5,4,3,5,6
1,5,5,6,5,6,3,1,5,5,6,4,4,3,2,5,3,5,3,2,4
2,3,4,5,2,4,5,5,4,5,4,3,4,5,6,6,6,4,5,4,5
3,5,5,4,4,3,5,5,5,5,5,4,4,6,5,5,4,5,4,5,5
4,5,6,6,6,6,6,6,6,6,2,3,3,3,5,2,4,2,1,1,1

In [ ]:
# Facebook, INS, youtube VS meta

# Facebook VS meta


def calculate_competitive_advantage(facebook_df, meta1_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
    num_variables = [5, 4, 3, 4, 4]

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = facebook_df.iloc[:, start_index:start_index + measurements].gt(
                            meta1_df.iloc[:, start_index:start_index + measurements]).multiply(
                            facebook_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = meta1_df.iloc[:, start_index:start_index + measurements].gt(
                            facebook_df.iloc[:, start_index:start_index + measurements]).multiply(
                            meta1_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(facebook_df),
            'S_j_greater_i': M_j_greater_i / len(meta1_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage


# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(facebook_df, meta1_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2718,
  'M_j_greater_i': 1261,
  'S_i_greater_j': 15.620689655172415,
  'S_j_greater_i': 7.247126436781609},
 '오락': {'M_i_greater_j': 1440,
  'M_j_greater_i': 1855,
  'S_i_greater_j': 8.275862068965518,
  'S_j_greater_i': 10.660919540229886},
 '개인화': {'M_i_greater_j': 1210,
  'M_j_greater_i': 918,
  'S_i_greater_j': 6.954022988505747,
  'S_j_greater_i': 5.275862068965517},
 '상호작용': {'M_i_greater_j': 947,
  'M_j_greater_i': 2368,
  'S_i_greater_j': 5.442528735632184,
  'S_j_greater_i': 13.60919540229885},
 '만족': {'M_i_greater_j': 1603,
  'M_j_greater_i': 1543,
  'S_i_greater_j': 9.21264367816092,
  'S_j_greater_i': 8.867816091954023}}

In [ ]:
# Facebook, INS, youtube VS meta

# INS VS meta


def calculate_competitive_advantage(ins_df, meta1_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
    num_variables = [5, 4, 3, 4, 4]

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = ins_df.iloc[:, start_index:start_index + measurements].gt(
                            meta1_df.iloc[:, start_index:start_index + measurements]).multiply(
                            ins_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = meta1_df.iloc[:, start_index:start_index + measurements].gt(
                            ins_df.iloc[:, start_index:start_index + measurements]).multiply(
                            meta1_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(ins_df),
            'S_j_greater_i': M_j_greater_i / len(meta1_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage


# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(ins_df, meta1_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2989,
  'M_j_greater_i': 1215,
  'S_i_greater_j': 17.17816091954023,
  'S_j_greater_i': 6.982758620689655},
 '오락': {'M_i_greater_j': 1498,
  'M_j_greater_i': 1667,
  'S_i_greater_j': 8.60919540229885,
  'S_j_greater_i': 9.580459770114942},
 '개인화': {'M_i_greater_j': 1294,
  'M_j_greater_i': 905,
  'S_i_greater_j': 7.436781609195402,
  'S_j_greater_i': 5.2011494252873565},
 '상호작용': {'M_i_greater_j': 1321,
  'M_j_greater_i': 2069,
  'S_i_greater_j': 7.591954022988506,
  'S_j_greater_i': 11.89080459770115},
 '만족': {'M_i_greater_j': 1640,
  'M_j_greater_i': 1672,
  'S_i_greater_j': 9.425287356321839,
  'S_j_greater_i': 9.60919540229885}}

In [ ]:
youtube_df.head()

,정보1,정보2,정보3,정보4,정보5,오락1,오락2,오락3,오락4,개인화1,개인화2,개인화3,상호작용1,상호작용2,상호작용3,상호작용4,만족1,만족2,만족3,만족4
0,4,5,7,7,7,6,4,4,5,4,5,4,5,2,2,2,6,3,4,6
1,7,7,7,7,7,6,3,7,4,6,6,6,3,3,2,3,6,6,6,6
2,7,7,7,7,7,6,6,6,6,5,5,4,5,7,7,6,4,5,5,4
3,5,5,4,4,2,3,4,2,2,3,3,2,3,4,5,6,3,4,5,6
4,3,3,5,4,3,5,3,3,3,3,3,2,3,3,3,3,4,3,3,3

In [ ]:
# Facebook, INS, youtube VS meta

# youtube VS meta


def calculate_competitive_advantage(youtube_df, meta1_df, num_variables):

    competitive_advantage = {}

    # Variable names as given in the problem statement
    variable_names = ['정보', '오락', '개인화', '상호작용', '만족']

    # Number of measurements for each variable in the order: 정보, 오락, 상호작용, 개인화, 만족
    num_variables = [5, 4, 3, 4, 4]

    # Start index for each variable's measurements in the DataFrame
    start_index = 0

    # Loop through each variable by its number of measurements
    for var_index, measurements in enumerate(num_variables):
        # Calculate the sum of scores where media 1 has a higher score than media 2
        M_i_greater_j = youtube_df.iloc[:, start_index:start_index + measurements].gt(
                            meta1_df.iloc[:, start_index:start_index + measurements]).multiply(
                            youtube_df.iloc[:, start_index:start_index + measurements]).sum().sum()
        # Calculate the sum of scores where media 2 has a higher score than media 1
        M_j_greater_i = meta1_df.iloc[:, start_index:start_index + measurements].gt(
                            youtube_df.iloc[:, start_index:start_index + measurements]).multiply(
                            meta1_df.iloc[:, start_index:start_index + measurements]).sum().sum()

        # Calculate competitive advantage scores and add to dictionary
        competitive_advantage[variable_names[var_index]] = {
            'M_i_greater_j': M_i_greater_j,
            'M_j_greater_i': M_j_greater_i,
            'S_i_greater_j': M_i_greater_j / len(youtube_df),
            'S_j_greater_i': M_j_greater_i / len(meta1_df)
        }

        # Update the start index for the next variable
        start_index += measurements

    return competitive_advantage


# Calculate competitive advantage between Facebook and INS
comp_adv_fb_ins = calculate_competitive_advantage(youtube_df, meta1_df, num_variables)

comp_adv_fb_ins

{'정보': {'M_i_greater_j': 2716,
  'M_j_greater_i': 1383,
  'S_i_greater_j': 15.60919540229885,
  'S_j_greater_i': 7.948275862068965},
 '오락': {'M_i_greater_j': 1536,
  'M_j_greater_i': 1766,
  'S_i_greater_j': 8.827586206896552,
  'S_j_greater_i': 10.149425287356323},
 '개인화': {'M_i_greater_j': 1429,
  'M_j_greater_i': 768,
  'S_i_greater_j': 8.21264367816092,
  'S_j_greater_i': 4.413793103448276},
 '상호작용': {'M_i_greater_j': 1124,
  'M_j_greater_i': 2318,
  'S_i_greater_j': 6.459770114942529,
  'S_j_greater_i': 13.32183908045977},
 '만족': {'M_i_greater_j': 1597,
  'M_j_greater_i': 1722,
  'S_i_greater_j': 9.17816091954023,
  'S_j_greater_i': 9.89655172413793}}

# 경쟁우위(p-value)

In [ ]:
from scipy.stats import ttest_ind

# Facebook VS INS

# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = facebook_df[category_columns].sum(axis=1) - ins_df[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    fb_greater = diffs[diffs > 0]
    fb_greater_scores = facebook_df.loc[fb_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    insta_greater = diffs[diffs < 0]
    insta_greater_scores = ins_df.loc[insta_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(fb_greater_scores) > 1 and len(insta_greater_scores) > 1:
        t_stat, p_val = ttest_ind(fb_greater_scores, insta_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': -0.89003516212775, 'p_value': 0.37476683457233095},
 '오락': {'t_stat': 1.4119486725373747, 'p_value': 0.1598256774380776},
 '개인화': {'t_stat': -0.6872412407323137, 'p_value': 0.4929382404658955},
 '상호작용': {'t_stat': -0.17511745520137406, 'p_value': 0.8612046820316205},
 '만족': {'t_stat': 0.9854582016111068, 'p_value': 0.3258776865250238}}

In [ ]:
# Facebook VS youtube
# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = facebook_df[category_columns].sum(axis=1) - youtube_df[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    fb_greater = diffs[diffs > 0]
    fb_greater_scores = facebook_df.loc[fb_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    youtube_greater = diffs[diffs < 0]
    youtube_greater_scores = youtube_df.loc[youtube_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(fb_greater_scores) > 1 and len(youtube_greater_scores) > 1:
        t_stat, p_val = ttest_ind(fb_greater_scores, youtube_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': 0.16565797685366088, 'p_value': 0.8686264922391584},
 '오락': {'t_stat': -0.6745598105523962, 'p_value': 0.5009289860157604},
 '개인화': {'t_stat': -0.8020099703279457, 'p_value': 0.4237517934620373},
 '상호작용': {'t_stat': 0.17034243136944777, 'p_value': 0.8649482774664554},
 '만족': {'t_stat': -0.5754774130031854, 'p_value': 0.5657572191320371}}

In [ ]:
# Ins VS youtube

# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = ins_df[category_columns].sum(axis=1) - youtube_df[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    ins_greater = diffs[diffs > 0]
    ins_greater_scores = ins_df.loc[ins_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    youtube_greater = diffs[diffs < 0]
    youtube_greater_scores = youtube_df.loc[youtube_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(ins_greater_scores) > 1 and len(youtube_greater_scores) > 1:
        t_stat, p_val = ttest_ind(ins_greater_scores, youtube_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': -2.3487491155756164, 'p_value': 0.020021342316003925},
 '오락': {'t_stat': -0.549830057738655, 'p_value': 0.5832074389533771},
 '개인화': {'t_stat': -0.6377497783073495, 'p_value': 0.5245314424411347},
 '상호작용': {'t_stat': 1.7417134278560746, 'p_value': 0.0834335662043608},
 '만족': {'t_stat': -1.0679260979332583, 'p_value': 0.28720364773945467}}

In [ ]:
# SNS(rounded_df) VS meta

# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = rounded_df[category_columns].sum(axis=1) - meta_df[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    SNS_greater = diffs[diffs > 0]
    SNS_greater_scores = rounded_df.loc[SNS_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    meta_greater = diffs[diffs < 0]
    meta_greater_scores = meta_df.loc[meta_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(SNS_greater_scores) > 1 and len(meta_greater_scores) > 1:
        t_stat, p_val = ttest_ind(SNS_greater_scores, meta_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': -2.748786855847713, 'p_value': 0.00666075082027032},
 '오락': {'t_stat': -5.267935372173186, 'p_value': 4.3121953506898705e-07},
 '개인화': {'t_stat': -2.236753401219792, 'p_value': 0.026872288421541164},
 '상호작용': {'t_stat': -5.408124364343937, 'p_value': 2.249348896435814e-07},
 '만족': {'t_stat': -5.374256318389547, 'p_value': 2.6946403714316526e-07}}

In [ ]:
# Facebook VS meta

from scipy.stats import ttest_ind
# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = facebook_df[category_columns].sum(axis=1) - meta[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    facebook_greater = diffs[diffs > 0]
    facebook_greater_scores = facebook_df.loc[facebook_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    meta_greater = diffs[diffs < 0]
    meta_greater_scores = meta.loc[meta_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(facebook_greater_scores) > 1 and len(meta_greater_scores) > 1:
        t_stat, p_val = ttest_ind(facebook_greater_scores, meta_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': 2.3418985006339605, 'p_value': 0.02044981082964344},
 '오락': {'t_stat': -0.490574871541753, 'p_value': 0.6243789264438566},
 '개인화': {'t_stat': 2.598535930258863, 'p_value': 0.010225754196798116},
 '상호작용': {'t_stat': -1.1123545172902634, 'p_value': 0.26763370378664825},
 '만족': {'t_stat': -0.017754085391770754, 'p_value': 0.9858570162237118}}

In [ ]:
# INS VS meta

from scipy.stats import ttest_ind
# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = ins_df[category_columns].sum(axis=1) - meta[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    ins_greater = diffs[diffs > 0]
    ins_greater_scores = ins_df.loc[ins_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    meta_greater = diffs[diffs < 0]
    meta_greater_scores = meta.loc[meta_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(ins_greater_scores) > 1 and len(meta_greater_scores) > 1:
        t_stat, p_val = ttest_ind(ins_greater_scores, meta_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': 0.7940228047915064, 'p_value': 0.4283295739927403},
 '오락': {'t_stat': -0.02631384762987232, 'p_value': 0.9790384273387966},
 '개인화': {'t_stat': 4.026847015123063, 'p_value': 8.777585266017045e-05},
 '상호작용': {'t_stat': -0.6730537188398301, 'p_value': 0.5018780623545074},
 '만족': {'t_stat': -1.1652978341240487, 'p_value': 0.24563277113516663}}

In [ ]:
# youtube VS meta

from scipy.stats import ttest_ind
# Re-define the categories with their corresponding columns
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# Assume facebook_data and instagram_data DataFrames are already defined and loaded correctly
# Initialize a dictionary to store the t-test results
t_test_results = {}

# Loop through each category to perform the t-tests
for category_name, category_columns in categories.items():
    # Calculate the difference for each observation in the category
    diffs = youtube_df[category_columns].sum(axis=1) - meta[category_columns].sum(axis=1)

    # Extract the observations where Facebook > Instagram
    youtube_greater = diffs[diffs > 0]
    youtube_greater_scores = youtube_df.loc[youtube_greater.index, category_columns].sum(axis=1)

    # Extract the observations where Instagram > Facebook
    meta_greater = diffs[diffs < 0]
    meta_greater_scores = meta.loc[meta_greater.index, category_columns].sum(axis=1)

    # Perform t-test if both subsets have more than one observation, otherwise record as not applicable (NA)
    if len(youtube_greater_scores) > 1 and len(meta_greater_scores) > 1:
        t_stat, p_val = ttest_ind(youtube_greater_scores, meta_greater_scores)
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': 1.9061344865247762, 'p_value': 0.058403486848403935},
 '오락': {'t_stat': 0.1754314695950347, 'p_value': 0.860963828185172},
 '개인화': {'t_stat': 1.4646220231691374, 'p_value': 0.14498619358629275},
 '상호작용': {'t_stat': -0.24317441323924494, 'p_value': 0.8081779255421611},
 '만족': {'t_stat': 0.8091077334106257, 'p_value': 0.419654723520413}}

In [ ]:
from scipy.stats import ttest_ind

# 假定 'youtube_df' 和 'meta' 是已经正确定义和加载的包含相关类别列的DataFrame。

# 定义类别及其对应的列
categories = {
    '정보': ['정보1', '정보2', '정보3', '정보4', '정보5'],
    '오락': ['오락1', '오락2', '오락3', '오락4'],
    '개인화': ['개인화1', '개인화2', '개인화3'],
    '상호작용': ['상호작용1', '상호작용2', '상호작용3', '상호작용4'],
    '만족': ['만족1', '만족2', '만족3', '만족4']
}

# 初始化一个字典来存储t检验的结果
t_test_results = {}

# 循环每一个类别进行计算和t检验
for category_name, category_columns in categories.items():
    # 对于每个类别，计算YouTube和Metaverse的得分差异
    diffs = ins_df[category_columns].sum(axis=1) - meta[category_columns].sum(axis=1)

    # 提取得分中YouTube > Metaverse的情况
    ins_greater = diffs[diffs > 0]
    ins_greater_sum = ins_df.loc[ins_greater.index, category_columns].sum(axis=1)

    # 提取得分中Metaverse > YouTube的情况
    meta_greater = diffs[diffs < 0]
    meta_greater_sum = meta.loc[meta_greater.index, category_columns].sum(axis=1)

    # 计算条件得分总和的平均值
    ins_greater_avg_sum = ins_greater_sum.sum()/len(ins_df)
    meta_greater_avg_sum = meta_greater_sum.sum()/len(meta)

    # 检查是否有足够的数据点进行t检验
    if len(ins_greater_sum) > 0 and len(meta_greater_sum) > 0:
        t_stat, p_val = ttest_ind(ins_greater_sum, meta_greater_sum, equal_var=False)  # 使用Welch's t-test
        t_test_results[category_name] = {'t_stat': t_stat, 'p_value': p_val}
    else:
        t_test_results[category_name] = {'t_stat': 'NA', 'p_value': 'NA'}

t_test_results

{'정보': {'t_stat': 0.8314963915015149, 'p_value': 0.40754073660924417},
 '오락': {'t_stat': -0.026352686368523146, 'p_value': 0.9790086177475418},
 '개인화': {'t_stat': 4.0046196083227725, 'p_value': 9.884666767766253e-05},
 '상호작용': {'t_stat': -0.6708092751921358, 'p_value': 0.5034825826827363},
 '만족': {'t_stat': -1.1644778949040702, 'p_value': 0.2459752263757347}}